"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

import sys, os
sys.path.append(os.path.join(os.path.dirname(os.path.dirname(os.path.realpath(__file__))), "Lib"))
from ShowDB import ShowDB, ShowIDs

from setuptools import setup

APP = ['mediaprez.pyw']
DATA_FILES = []
OPTIONS = {'argv_emulation': True,
           'resources': "tag.trash,config.txt,htmlsrc",
           'packages': ['PIL']}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
